# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/notesapp
spring.datasource.username=root
spring.datasource.password=vishal@123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# App Port
server.port=8080

# JWT Secret Key
jwt.secret=notesapp_super_secret_key_123456789_abcdefgh
jwt.expiration=86400000

spring.jpa.open-in-view=false